### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by africola**
German translation -- untested, please check and review before merging

### CODE REVIEW

**Comment by Strauman** [comment]
Looks good! I'll update to CTAN today at some point with some other changes!

**Comment by Strauman** [comment]
@africola I hope it's okay that I added your github profile for credits into the documentation?

**Comment by Strauman** [comment]
Pushed to CTAN in b056570

**Comment by africola** [comment]
@Strauman Yes, adding a link to my Github profile is fine. Thanks for the merge & the package!

**Pull request merged**
